"""Add all final columns to items and categories

Revision ID: 17a5bbb75a22
Revises: 7cbe54b39751
Create Date: 2025-10-16 04:17:40.143997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17a5bbb75a22'
down_revision: Union[str, None] = '7cbe54b39751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('availability_rule', sa.String(), nullable=True))
    op.add_column('items', sa.Column('disabled_dates', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'disabled_dates')
    op.drop_column('items', 'availability_rule')
    # ### end Alembic commands ###
